// <auto-generated />
namespace CASHIR_SYSTEM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class bfsd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bfsd));
        
        string IMigrationMetadata.Id
        {
            get { return "202010111646395_bfsd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
